### ISSUE TITLE
No index settings fields for elasticsearch

### ISSUE THREAD

**Issue by bernhardriegler** [gentics/mesh-incubator#22] opened 2019-05-07 07:08 UTC
Not all fields are need to be indexed in elasticsearch.
There is no option to prevent indexing, which inflates the index.

There should be a setting in the schema to prevent certain fields from being indexed.

**Comment by Jotschi** [comment] 2019-07-02 14:15
Duplicate of #190

**Closed by Jotschi** 2019-07-02 14:15 UTC
